# Docker Compose file to easily run both frontend and backend locally. This is just for local development purposes.

services:
  # Frontend service
  frontend:
    build:
      # Use frontend folder as build context
      context: ./frontend
      # Use the Dockerfile in the context folder
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Depends on backend to run first
    depends_on:
      - backend
    networks:
      - fe_be

  # Backend service
  backend:
    build:
      # Use backend folder as build context
      context: ./backend
      # Use the Dockerfile in the context folder
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    # Load a .env file with the container for the backend
    env_file:
      # Use .env file in the build context folder
      - .env
    networks:
      - fe_be

# Define networks (In Docker Compose, a network allows containers to communicate with each other 
# without exposing their ports to the host machine. It creates an isolated environment where services 
# can interact using container names instead of IP addresses.)
networks:
  # Define network for frontend and backend: https://docs.docker.com/reference/compose-file/networks/
  fe_be:
    # Use bridge driver to communicate with other containers on the same host: https://docs.docker.com/engine/network/drivers/
    driver: bridge
