# Docker Compose file used for deployment (should be called docker-compose.yml, as this is used by AWS directly)

services:
  # Frontend service
  frontend:
    # Use the image from the Docker Hub
    image: poetoecuva/rac-frontend:latest
    # Define ports: "HOST_PORT:CONTAINER_PORT": https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/
    ports:
      # This forwards any traffic send through port 80 (main port on AWS EB instace) to container port 3000 (frontend container)
      - "80:3000"
    # Add environment variables (only the required ones) from the AWS EB environment (env vars set in deploy.yml)
    environment:
      - NEXT_PUBLIC_FRONTEND_URL
      - NEXT_PUBLIC_BACKEND_FULL_URL
    # Depends on backend to run first
    depends_on:
      - backend
    networks:
      - fe_be

  # Backend service
  backend:
    image: poetoecuva/rac-backend:latest
    ports:
      - "4001:4001"
    # Add environment variables (only the required ones) from the AWS EB environment (env vars set in deploy.yml)
    environment:
      - MONGO_URI
      - SECRET_KEY
      - FACTOR
      - ROLE
      - API_NAME
      - API_PORT
      - API_VERSION
      - FRONTEND_URL
      - BACKEND_URL
      - VEHICLE_URL
      - S3_BUCKET_NAME
    networks:
      - fe_be

# Define networks (In Docker Compose, a network allows containers to communicate with each other 
# without exposing their ports to the host machine. It creates an isolated environment where services 
# can interact using container names instead of IP addresses.)
networks:
  # Define network for frontend and backend: https://docs.docker.com/reference/compose-file/networks/
  fe_be:
    # Use bridge driver to communicate with other containers on the same host: https://docs.docker.com/engine/network/drivers/
    driver: bridge
