# Docker Compose file used for deployment (should be called docker-compose.yml, as this is used by AWS directly)
# This now uses only one container, but that is fine for Docker Compose, as this allows for easy configuration and setup

services:
  # Backend service
  backend:
    image: poetoecuva/rac-backend:latest
    # Define ports: "HOST_PORT:CONTAINER_PORT": https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/
    ports:
      # This forwards any traffic send through port 80 (default incoming traffic port for AWS EB) to container port 4001 (backend container)
      - "80:4001"
    # Load a .env file with the container for the backend
    env_file:
      # Use .env file from the root of the project
      # (Here the .env file is loaded all at once in the deployed environment, so can just be .env in root now)
      - .env