- name: Create AWS S3 Bucket
  hosts: localhost
  gather_facts: no
  # Loads variables from vars.yml
  vars_files:
    - vars.yml
  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ s3.bucket_name }}"
        region: "{{ global.aws_region }}"
        acl: "{{ s3.bucket_acl }}"
        versioning: "{{ s3.enable_versioning }}"

    - name: Display S3 Bucket Information
      debug:
        msg: "S3 bucket created with name: {{ s3_bucket_info.name }}"

# TODO: remove this file later, this is just for testing the variables, but Terraform is used to provision (create infrastructure)