name: Continuous Integration - Build, Test & Push

# Specify this workflow can be called by another workflow using workflow_call: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_call
on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    # Use the main environment from GitHub to load environment variables
    environment: main
    # Use strategy to run this step multiple times with the possible services
    # Documentation: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
    strategy:
      matrix:
        service: [backend, frontend]  # Runs for both services
    steps:
    # Step 0: Set IMAGE_TAG environment variable for this specific service
    - name: Set Image Tag
      # This will set a variable in the $GITHUB_ENV file, which is available within this specific job 
      run: |
        IMAGE_TAG="${{ env.DOCKER_REGISTRY }}/rac-${{ matrix.service }}:latest"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    # Step to confirm IMAGE_TAG
    - name: Print IMAGE_TAG
      run: echo "Using IMAGE_TAG=${IMAGE_TAG}"

    # Step 1: Build Docker images
    - name: Build Docker images 
      uses: ./.github/workflows/ci/build.yml
      with:
        service: ${{ matrix.service }}
        image_tag: ${{ env.IMAGE_TAG }}
    # Fail early if builds fail to avoid going to the next steps
    # This is required manually here, since this allows reusing strategy and matrix, and image_tag in the ci job. 
    # The "needs" column can therefore not be set and we fail manually here
    - name: Fail if builds fail
      if: failure()
      run: exit 1

    # Step 2: Run tests
    - name: Run Tests
      uses: ./.github/workflows/ci/test.yml
      with:
        service: ${{ matrix.service }}
        image_tag: ${{ env.IMAGE_TAG }}
    # Fail early if tests fail to avoid going to the next steps
    # This is required manually here, for the same reason as above for the build manual failure
    - name: Fail if tests fail
      if: failure()
      run: exit 1

    # Step 3: Push images to Docker Hub
    - name: Push images to Docker Hub
      uses: ./.github/workflows/ci/push.yml
      with:
        service: ${{ matrix.service }}
        image_tag: ${{ env.IMAGE_TAG }}
