name: Push Docker Image

# Specify this workflow can be called by another workflow using workflow_call: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_call
on:
  workflow_call:
    # Use input variables for this step
    inputs:
      service:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    # Push image to Docker Hub if builds and tests were successful
    # (Should already be logged in to Docker Hub after setup.yml)
    - name: Push Docker Image to Docker Hub
      run: docker push "${IMAGE_TAG}"
