# Ansible dependencies (collections)
collections:
  # AWS modules: https://docs.ansible.com/ansible/latest/collections/amazon/aws/index.html#plugins-in-amazon-aws
  - name: amazon.aws
    version: 9.1.1
