name: Build Docker Images

# Specify this workflow can be called by another workflow using workflow_call: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_call
on:
  workflow_call:
    # Input variables
    inputs:
      BE_IMAGE_NAME:
        required: true
        type: string
      FE_IMAGE_NAME:
        required: true
        type: string
      DOCKER_REGISTRY:
        required: true
        type: string

jobs:
  
