name: Build Docker Image

# Specify this workflow can be called by another workflow using workflow_call: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_call
on:
  workflow_call:
    # Use input variables for this step
    inputs:
      service:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step to build the Docker image
    # First go into the service folder and then build the image
    - name: Build Docker Image
      run: |
        cd ${{ inputs.service }}
        docker build --build-arg NAME="rac-${{ inputs.service }}" -t "${{ inputs.image_tag }}" .
