name: Deploy Frontend & Backend to AWS Elastic Beanstalk

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  # Job to deploy backend
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    # Use the main environment from GitHub to load environment variables
    environment: main
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.SECRET_ACCESS_KEY }}

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli zip

    - name: Package Backend Application
      run: |
        cd backend
        zip -r ../backend-deploy.zip Dockerrun.aws.json .ebextensions

    - name: Upload Backend to S3
      run: |
        aws s3 cp backend-deploy.zip s3://${{ secrets.S3_BUCKET }}/backend-deploy.zip

    - name: Deploy Backend to AWS Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name BackendApp \
          --version-label "backend-${{ github.run_number }}" \
          --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="backend-deploy.zip"

        aws elasticbeanstalk update-environment --environment-name ${{ secrets.BACKEND_ENV_NAME }} \
          --version-label "backend-${{ github.run_number }}"

# deploy-frontend:
#   name: Deploy Frontend
#   runs-on: ubuntu-latest
#   needs: deploy-backend  # Ensures backend deploys first

#   steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v4

#     - name: Install AWS CLI
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y awscli zip

#     - name: Update Frontend Backend URL
#       run: |
#         sed -i "s|REACT_APP_BACKEND_URL=.*|REACT_APP_BACKEND_URL=https://${{ secrets.BACKEND_ENV_NAME }}.elasticbeanstalk.com|" frontend/.env.production

#     - name: Package Frontend Application
#       run: |
#         cd frontend
#         zip -r ../frontend-deploy.zip Dockerrun.aws.json .ebextensions

#     - name: Upload Frontend to S3
#       run: |
#         aws s3 cp frontend-deploy.zip s3://${{ secrets.S3_BUCKET }}/frontend-deploy.zip

#     - name: Deploy Frontend to AWS Elastic Beanstalk
#       run: |
#         aws elasticbeanstalk create-application-version --application-name FrontendApp \
#           --version-label "frontend-${{ github.run_number }}" \
#           --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="frontend-deploy.zip"

#         aws elasticbeanstalk update-environment --environment-name ${{ secrets.FRONTEND_ENV_NAME }} \
#           --version-label "frontend-${{ github.run_number }}"
