name: Push Docker Image

# Specify this workflow can be called by another workflow using workflow_call: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_call
on:
  workflow_call:

jobs:
  push:
    runs-on: ubuntu-latest
    # Use the main environment from GitHub to load environment variables
    environment: main
    # Use strategy to run this step multiple times with the possible services
    # Documentation: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
    strategy:
      matrix:
        service: [backend, frontend]  # Runs for both services
    steps:
    # Push image to Docker Hub if builds and tests were successful
    # (Should already be logged in to Docker Hub after setup.yml)
    - name: Push Docker Image to Docker Hub
      run: docker push "${IMAGE_TAG}"
