name: Test Docker Image

# Specify this workflow can be called by another workflow using workflow_call: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_call
on:
  workflow_call:
    # Use input variables for this step
    inputs:
      service:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Manually create a .env file in this job with the environment variables for each service
    # > creates (or overwrites) the file .env, and >> appends to the file (adds content to an existing file)
    # Names must be exactly the same as the dummy.env files, otherwise the variables cannot be found by the source code
    - name: Create .env file (backend)
      if: inputs.service == 'backend'
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "FACTOR=${{ secrets.FACTOR }}" >> .env
        echo "ROLE=${{ secrets.ROLE }}" >> .env
        echo "API_NAME=${{ vars.API_NAME }}" >> .env
        echo "API_PORT=${{ vars.API_PORT }}" >> .env
        echo "API_VERSION=${{ vars.API_VERSION }}" >> .env
        echo "FRONTEND_URL=${{ vars.FRONTEND_URL }}" >> .env
        echo "BACKEND_URL=${{ vars.BACKEND_URL }}" >> .env
        echo "VEHICLE_URL=${{ vars.VEHICLE_URL }}" >> .env
    # Create a different .env file for the frontend
    - name: Create .env file (frontend)
      if: inputs.service == 'frontend'
      run: |
        echo "NEXT_PUBLIC_FRONTEND_URL=${{ vars.NEXT_PUBLIC_FRONTEND_URL }}" >> .env
        echo "NEXT_PUBLIC_BACKEND_FULL_URL=${{ vars.NEXT_PUBLIC_BACKEND_FULL_URL }}" >> .env
    
    # Step to run Docker container
    # Run docker in detached mode (-d) to run the container in the background
    # Use the .env file just created, since -e caused the docker run command to crash, specifically MONGO_URI for backend
    # Select the correct port using the service
    - name: Run Container with Environment Variables
      run: |
        if [ "${{ inputs.service }}" == "backend" ]; then
          PORT=${{ vars.API_PORT }}
        else
          PORT=${{ vars.FRONTEND_PORT }}
        fi

        docker run -d \
          --env-file .env \
          -p $PORT:$PORT \
          --name rac-${{ inputs.service }} \
          ${{ inputs.image_tag }}
    
    # Delete the .env file just to be sure (probably also done automatically, but for security reasons manually delete it as well)
    - name: Delete .env File After Use
      run: rm -f .env

    # Step to wait for the container to be ready and running tests
    # "until curl -s" silently tries to fetch the backend URL, retrying every 2 seconds 
    # and timing out after 15 seconds
    - name: Wait for Container to Start
      run: |
        if [ "${{ inputs.service }}" == "backend" ]; then
          CONTAINER_URL=${{ vars.BACKEND_URL }}
        else
          CONTAINER_URL=${{ vars.FRONTEND_URL }}
        fi

        echo "Waiting for container $IMAGE_TAG to be ready at $CONTAINER_URL..."
        timeout 15 sh -c "until curl -s $CONTAINER_URL; do sleep 2; done"
        echo "Container is ready!"
    
    
    # Step to run `npm run test` inside the running container
    # (environment variables should already be present in the docker container, as they are set in the docker run step)
    - name: Run Container Tests and Stop Container After Tests
      run: |
        if [ "${{ inputs.service }}" == "backend" ]; then
          IMAGE_NAME=${{ env.BE_IMAGE_NAME }}
        else
          IMAGE_NAME=${{ env.FE_IMAGE_NAME }}
        fi

        docker exec $IMAGE_NAME npm run test

        docker stop $IMAGE_NAME
        